### ISSUE TITLE
Agregar nueva pestaña

### ISSUE THREAD

**Issue by agrometeorologia1laura** [AgRoMeteorologiaINTA/SistemaAnguil#12]
Agregar una nueva pestaña: ESTADISTICAS DATOS ANGUIL
Importante: que quede habilitada para subir archivos de tipo .xls y .pdf
(Luego nosotros iremos subiendo los archivos a medida de que vayan actualizándose)

**Comment by GitHubJotaPe** [comment]
Tiene que ser parecida a alguna otra pagina del sitio que ya este desarrollada, y con una nomenclatura acorde, así se puede automatizar.
Si es como la sección de "Informes tecnicos y publicaciones"; va a ser casi todo a mano.

Otra cosa es saber si se esos archivos se van a mostrar directamente en la página; o si se va a poner un link, que al hacer click se abra la pagina de github mostrando el archivo.
Ej: si se hace click en el link siguiente, se ve directamente el informe
https://github.com/AgRoMeteorologiaINTA/SistemaAnguil/blob/main/www/informes/Informe%20Heladas%20marzo%202022.pdf

**Comment by agrometeorologia1laura** [comment]
Con respecto a:
 "_### _Otra cosa es saber si se esos archivos se van a mostrar directamente en la página; o si se va a poner un link, que al hacer click se abra la pagina de github mostrando el archivo.
Ej: si se hace click en el link siguiente, se ve directamente el informe
https://github.com/AgRoMeteorologiaINTA/SistemaAnguil/blob/main/www/informes/Informe%20Heladas%20marzo%202022.pdf"__
**Creo que lo que te resulte mas comodo de hacer, personalmente me gusta el link, como el ejemplo.
Es importante tambien que puedan descargarse**

**Comment by GitHubJotaPe** [comment]
Se agregó la pestaña.
Luego cuando se tengan los archivos, vamos subiendo algunos para ver como se visualizan (mas que nada los excels)

**Comment by agrometeorologia1laura** [comment]
Ok, mañana ya miro si tenemos algunos listos para mostrarte JP

**Comment by GitHubJotaPe** [comment]
Ahi subí algo como para ver que parece.
El unico botón que anda es el de Enero de 2020, que es el que tiene archivo excel para descargar.

**Comment by agrometeorologia1laura** [comment]
Ahi probé, está perfecto. No previsualiza solo solicita descarga
