### ISSUE TITLE
Agregar links a su respectiva pestaña

### ISSUE THREAD

**Issue by agrometeorologia1laura** [AgRoMeteorologiaINTA/SistemaAnguil#13]
https://inta.gob.ar/anguil  (INTA EEA Anguil)
https://inta.gob.ar/clima-y-agua (INTA Instituto de Clima y Agua)
http://siga.inta.gob.ar/#/  (INTA Sistema de Información y Gestión Agrometeorológica)
http://www.geointa.inta.gob.ar/ (INTA Geointa)
https://radar.inta.gob.ar/  (Radares Meteorológicos de INTA)
http://sepa.inta.gob.ar/ (INTA ICyA Herramientas satelitales para el seguimiento de la producción agropecuaria)
https://inta.gob.ar/documentos/pronosticos (INTA Pronósticos a corto plazo)
https://www.smn.gob.ar/ (Servicio Meteorológico Nacional)
https://lapampa.redesclimaticas.com/accounts/ (Gob. de La Pampa Red de Estaciones Climáticas)

**Comment by GitHubJotaPe** [comment]
Para despejar dudas, todos estos links van en la pestaña "links" ?

**Comment by agrometeorologia1laura** [comment]
**Para despejar dudas, todos estos links van en la pestaña "links" ?**
Asi es
