### ISSUE TITLE
Agregar más “botoneras” de años y sus meses correspondientes en los ítems “repositorios SIG y Estadísticas datos Anguil 

### ISSUE THREAD

**Issue by agrometeorologia1laura** [AgRoMeteorologiaINTA/SistemaAnguil#18]
Convendría que quede por lo menos hasta 2025), así ya por un tiempo podemos seguir cargando los archivos sin problemas.

**Comment by GitHubJotaPe** [comment]
Agregado en el archivo.
R/cartografia.R
