### ISSUE TITLE
botón de CARTOGRAFIA 

### ISSUE THREAD

**Issue by agrometeorologia1laura** [AgRoMeteorologiaINTA/SistemaAnguil#19]
Si es posible: se despliegue para su vista las subsecciones que tiene (sin necesidad de clikear el mouse)….. ésto es porque en esa sección hay mucha más información y sería importante que esté más visible…..

**Comment by GitHubJotaPe** [comment]
Estuve probando algunas opciones, pero no las estoy pudiendo hacer andar.
Otra cosa: en celular o tablet, esto no se va a poder replicar (ya que no hay un mouse o puntero).

La otra opción, es separalo en sub-menúes, como está en "**Indices Agromet**".. , "**Registros históricos**", o "**Radar**"

**Comment by GitHubJotaPe** [comment]
Hecho en:
https://agrometeorologialapampa.shinyapps.io/SistemaAnguil/

Se pasó la sección **Cartografía** a sub-menúes
