### ISSUE TITLE
Solicitar cambio de fuente de datos (Item: Indices agrometeorologicos)

### ISSUE THREAD

**Issue by agrometeorologia1laura** [AgRoMeteorologiaINTA/SistemaAnguil#25]
Dado los problemas técnicos del sistema SIGA de donde se nutren los modelos usados , y que la fuente de obtencion de datos para el calculo de estos indices es actualmente es la estacion automatica (Identificador: A872823). Solicitamos si se podria cambiar nuevamente la fuente de datos a estacion convencional (Estación: INTA - Anguil EMC Identificador: NH0446)

**Comment by GitHubJotaPe** [comment]
Todavia no lo subí.

Estuve comparando los datos de NH0446, y hay algunas diferencias que afectan puntualmente a **Viento Máximo** y la **Rosa de los vientos**


```
velocidad_viento_maxima
> summary(A872823$velocidad_viento_maxima)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   7.20   21.00   26.60   27.76   33.10   81.70     323 
> summary(NH0446$velocidad_viento_maxima)
   Mode    NA's 
logical   22090 

direccion_viento_200cm
> summary(as.factor(A872823$direccion_viento_200cm))
        C    E    N   NE   NW    S   SE    W 
 132 1032  473   87  560  148  541   65  252 
> summary(as.factor(NH0446$direccion_viento_200cm))
          C 
22087     3 
> NH0446 %>% select(fecha, direccion_viento_200cm) %>% filter(direccion_viento_200cm == "C")
        fecha direccion_viento_200cm
1: 2015-02-24                      C
2: 2015-02-25                      C
3: 2015-02-26                      C
```
_NH0446$velocidad_viento_maxima_, no tiene datos
y 
_NH0446$direccion_viento_200cm_, tiene solamente 3 datos en C, y los demás vacíos.

No se si quieren dejarlas, graficar otras, o si las sacamos.

**Comment by agrometeorologia1laura** [comment]
Si JP, es asi la convencional (NH0446) no tiene registros del viento a 200 con la intensidad correspondiente, por lo tanto si tomamos los datos desde acá es imposible graficar eso. Como estamos en esta situacion donde necesitamos cambiar la fuente de datos (por problemas que no podemos solucionar por ahora) vamos a tener que dejar sin graficar vientos max y la rosa de vientos.
Pero si es factible, dejar la posibilidad de que se puedan seguir generando estos graficos ni bien se solucione el problema y podamos nuevamente tomar registros de A872823, que es lo mas conveniente.

**Comment by GitHubJotaPe** [comment]
Hecho en
https://agrometeorologialapampa.shinyapps.io/SistemaAnguil/

Se cambió la fuente de datos.
El código de la rosa de los vientos y viento máximo, queda comentado, para volver a ponerlo en un futuro.
