### ISSUE TITLE
Agregar foot con los datos de INTA

### ISSUE THREAD

**Issue by yabellini** [AgRoMeteorologiaINTA/SistemaAnguil#3]
Como pie en todas las páginas agregaríamos el logo de INTA y los siguientes datos:

Estación Experimental Agropecuaria Anguil "Ing. Agr. Guillermo Covas". Ruta Nacional N| 5. Km 580. (6326) Anguil, La Pampa. 02954-495057 - @intaanguil

**Comment by LoreCasares** [comment]
Si si, le da un aspecto mas formal

**Comment by GitHubJotaPe** [comment]
Se puso el footer de color clásico. 
Despues cuando se defina lo del  issue #4 , lo reabrimos y hacemos los cambios esteticos.
