### ISSUE TITLE
Cambios estéticos

### ISSUE THREAD

**Issue by yabellini** [AgRoMeteorologiaINTA/SistemaAnguil#4]
- Que el fondo de toda la web sea blanco para que quede mejor con respecto de los fondos de los gráficos.
- Aumentar la fuente a todo el sitio.

**Comment by LoreCasares** [comment]
Coincido

**Comment by GitHubJotaPe** [comment]
Subi un selector de _temas_  para que vean si hay alguno que les guste mas que otro.
Va a aparecer arriba a la derecha.
Sinó, sacamos el _tema_ de ahora (superhero), y tomamos como base el _tema_ original (sin shinytheme)

https://agrometeorologialapampa.shinyapps.io/SistemaAnguilTest/

**Comment by yabellini** [comment]
Me gustan flaty o cerulean.

**Comment by agrometeorologia1laura** [comment]
Ok, cerramos entonces con cualquiera de las dos propuestas de Yani.
Francisco sugiere poner el fondo un gris oscuro y el texto blanco y achicarle un toque el tamaño. Y en la cabecera, agregarle el logo de INTA.
Asi que culminamos asi.
Entonces ya vamos cerrando ésto. recordemos que ya iremos difuendiendo la pagina, asique el sitio en "su inicio" al menos debveria estar completo.

**Comment by GitHubJotaPe** [comment]
Puse el shinytheme: "flatly", ya que me pareció el mas parecido con el footer recomendado por Francisco.

El logo del INTA, lo saque de la pagina:
https://inta.gob.ar/documentos/mapas-de-indice-de-sequia-provincia-de-la-pampa-2015-2019
El actual, tiene una altura de 40 pixeles. 
Adjunto una imagen con una altura de 20 pixeles, por si les gusta mas.
![imagen](https://user-images.githubusercontent.com/7819529/164745946-d8504fbc-5d3b-4751-b210-8523347c21c9.png)

Igualmente, habría que pedirle a Francisco una imagen de buena calidad o en formato .svg y probar.
